/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mintshell_terminal_ncurses_interfaces_NCursesTerminal_TerminalInputStream */

#ifndef _Included_org_mintshell_terminal_ncurses_interfaces_NCursesTerminal_TerminalInputStream
#define _Included_org_mintshell_terminal_ncurses_interfaces_NCursesTerminal_TerminalInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef org_mintshell_terminal_ncurses_interfaces_NCursesTerminal_TerminalInputStream_MAX_SKIP_BUFFER_SIZE
#define org_mintshell_terminal_ncurses_interfaces_NCursesTerminal_TerminalInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#ifdef __cplusplus
}
#endif
#endif
