/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mintshell_terminal_ncurses_interfaces_NCursesTerminal_TerminalOutputStream */

#ifndef _Included_org_mintshell_terminal_ncurses_interfaces_NCursesTerminal_TerminalOutputStream
#define _Included_org_mintshell_terminal_ncurses_interfaces_NCursesTerminal_TerminalOutputStream
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
